### ISSUE TITLE
This repo has been deprecated. 

### ISSUE THREAD

**Issue by budparr** [sonnetmedia/missionfocus.com#16]
@ryandeussing FYI - 
I just merged this repo into the client's pre-existing Gitlab repo. Please do any future work in the client's Gitlab repo. I suppose issues can remain here (?). 

See podio for credentials for Gitlab

**Comment by ryandeussing** [comment]
Awesome, thx


On Tue, Sep 15, 2015, at 11:53 AM, Bud Parr wrote:
> @ryandeussing[1] FYI -
>
I just merged this repo into the client's pre-existing Gitlab repo.
Please do any future work in the client's Gitlab repo. I suppose issues
can remain here (?).


> See podio for credentials for Gitlab


> — Reply to this email directly or view it on GitHub[2].


>



Links:

  1. https://github.com/ryandeussing
  2. https://github.com/sonnetmedia/missionfocus.com/issues/16
